Task6_Django/mydjangoproject/mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
from myapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PatientListView.as_view(), name='home'),
    path('patient/<int:pk>/', AboutPatient.as_view(), name='patient'),
    path('form/', addPatient, name='form'),
    path('changedata/', PatientChangeListView.as_view(), name='changedata'),
    path('changedata/form/patient/<int:pk>/', ChangePatient.as_view(), name='changeform'),
]

Task6_Django/mydjangoproject/myapp/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    first_name = models.CharField(max_length=20, blank=False)
    last_name = models.CharField(max_length=20, blank=False)
    specialization = models.CharField(max_length=40, blank=False)
    experience = models.IntegerField(blank=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Room(models.Model):
    number = models.IntegerField(blank=False)
    department = models.CharField(max_length=40, blank=False)

    def __str__(self):
        return str(self.number)

class Patient(models.Model):
    first_name = models.CharField(max_length=20, blank=False)
    last_name = models.CharField(max_length=20, blank=False)
    age = models.IntegerField(blank=False)
    diagnosis = models.CharField(max_length=40, blank=False)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return f'/patient/{self.pk}/'

Task6_Django/mydjangoproject/myapp/views.py
from django.shortcuts import render, redirect
from myapp.form import AddPatient
from myapp.models import *
from django.views.generic import ListView, DetailView, UpdateView


# Create your views here.

class PatientListView(ListView):
    model = Patient
    template_name = 'medical/index.html'

class AboutPatient(DetailView):
    model = Patient
    template_name = 'medical/aboutPatient.html'

def addPatient(request):
    if request.method == 'POST':
        form = AddPatient(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AddPatient()
    return render(request, 'medical/form.html', {'form': form})

def changePatient(request):
    if request.method == 'POST':
        form = AddPatient(request.Post)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AddPatient()
    return render(request, 'medical/changePatient.html', {'form': form})
class PatientChangeListView(ListView):
    model = Patient
    template_name = 'medical/changedata.html'

class ChangePatient(UpdateView):
    model = Patient
    template_name = 'medical/changePatient.html'
    fields = ['first_name', 'last_name', 'age', 'diagnosis', 'doctor', 'room']

Task6_Django/mydjangoproject/templates/medical/aboutPatient.html
{% block title %}<title>Подробно о пациенте</title>{% endblock %}
{% block content %}
  <h1>Пациент\ка: {{ patient.first_name }} {{ patient.last_name }} </h1>
  <p><strong>ID:</strong> {{patient.pk}} </p>
  <p><strong>Возраст:</strong> {{patient.age}} </p> <!-- author detail link not yet defined -->
  <p><strong>Диагноз:</strong> {{patient.diagnosis}}</p>
  <p><strong>Лечащий Врач:</strong> {{patient.doctor}}</p>
  <p><strong>Палата:</strong> {{patient.room}}</p>

 <a href="{%url 'home'%}" > На главную страницу </a>
{% endblock %}

Task6_Django/mydjangoproject/templates/medical/changePatient.html
{% block title %}<title>Изменяем данные о пациенте</title>{% endblock %}
{% block content %}
    <h1>Редактирование</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock content %}

Task6_Django/mydjangoproject/templates/medical/changedata.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% block title %}<title>Изменяем данные</title>{% endblock %}
      <div class="col-sm-10 ">
      {% block content %}
           <h1>Список Пациентов</h1>
      {% if object_list %}
      <ul>
      {% for patient in patient_list %}
      <li>
        <a href="form{{patient.get_absolute_url}}">{{ patient.last_name }} {{patient.first_name}}</a> ({{patient.diagnosis}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no patients in the library.</p>
    {% endif %}
    {% endblock %}
     </div>

Task6_Django/mydjangoproject/templates/medical/form.html
{% block title %}<title>Форма</title>{% endblock %}
{% block content %}
  <h1>Заполните форму</h1>
  <form action="{% url 'form' %}" method="post">
    {% csrf_token %}
    <div class="form-error">{{form.non_field_errors}}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Добавить</button>
  </form>
{% endblock %}

Task6_Django/mydjangoproject/templates/medical/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% block title %}<title>Главная страница</title>{% endblock %}
      <div class="col-sm-10 ">
      {% block content %}
           <h1>Список Пациентов</h1>
      {% if object_list %}
      <ul>
      {% for patient in patient_list %}
      <li>
        <a href="{{patient.get_absolute_url}}">{{ patient.last_name }} {{patient.first_name}}</a> ({{patient.diagnosis}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no patients in the library.</p>
    {% endif %}
    <a href="{%url 'form' %}">Добавить пациента</a></li>
    {% endblock %}
      </div>